# Generated by Django 2.0.4 on 2018-05-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.CharField(choices=[('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Golden State Warriors', 'Golden State Warriors'), ('Boston Celtics', 'Boston Celtics'), ('Houson Rockets', 'Houston Rockets')], max_length=30)),
                ('age', models.IntegerField(max_length=2)),
            ],
        ),
    ]
