# Generated by Django 2.0.4 on 2018-05-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20180529_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Game1', 'Game1'), ('Game2', 'Game2'), ('Game3', 'Game3'), ('Game4', 'Game4'), ('Game5', 'Game5'), ('Game6', 'Game6'), ('Game7', 'Game7')], max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assists', models.DecimalField(decimal_places=2, max_digits=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Points'),
        ),
    ]
