# Generated by Django 2.0.4 on 2018-05-29 19:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20180529_1658'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='points',
            managers=[
                ('points_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
