# Generated by Django 2.0.4 on 2018-05-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20180529_1921'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='points',
            managers=[
            ],
        ),
    ]
