# Generated by Django 2.0.4 on 2018-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.CharField(choices=[('ESPN', 'ESPN'), ('FOX', 'FOX'), ('TNT', 'TNT'), ('ABC', 'ABC'), ('ESPN2', 'ESPN2')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='game_date',
            field=models.DateTimeField(null=True),
        ),
    ]
